language: cpp

script:
    - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc-4.8 valgrind
    - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 20
    - sudo update-alternatives --config gcc
    - sudo apt-get install -qq mercurial libsdl-dev
    - sudo apt-get install -qq libgtest-dev google-mock
    - sudo apt-get install -qq libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev libboost-wave-dev
    - gcc --version
    - sudo mkdir /usr/src/gtest/build
    - cd /usr/src/gtest/build
    - sudo cmake .. -DBUILD_SHARED_LIBS=1
    - sudo make -j`grep -c processor /proc/cpuinfo`
    - cd -
    - mkdir ./lib
    - sudo ln -s /usr/src/gtest/build/libgtest.so /usr/local/lib/libgtest.so
    - sudo ln -s /usr/src/gtest/build/libgtest_main.so /usr/local/lib/libgtest_main.so
    - hg clone https://bitbucket.org/jice/libtcod
    - cd libtcod
    - make -f makefiles/makefile-linux debug
    - cp ./libtcod_debug.so ../lib/libtcod_debug.so
    - cp ./libtcodxx_debug.so ../lib/libtcodxx_debug.so
    - cp ./libtcod_debug.so ../lib/libtcod.so
    - cp ./libtcodxx_debug.so ../lib/libtcodxx.so
    - cd -
    - cd lib
    - ln -s libtcod.so libtcod.so.1
    - ln -s libtcodxx.so libtcodxx.so.1
    - cd -
    - pwd
    - mkdir build
    - cd build
    - cmake ..
    - make -j`grep -c processor /proc/cpuinfo`
    - LD_LIBRARY_PATH=../lib valgrind --error-exitcode=1 --track-origins=yes --leak-check=full ./ut_amarlon

notifications:
  recipients:
    - lgromanowski+travis.ci@gmail.com
    - michal.lonski+travis.ci@gmail.com
  email:
    on_success: change
    on_failure: always
