language: cpp

script:
    - echo "yes" | sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu `lsb_release -sc` main universe restricted multiverse"
    - sudo apt-get update -qq
    - sudo apt-get install -qq gcc
    - sudo apt-get install -qq libgtest-dev google-mock
    - sudo apt-get install -qq libboost-filesystem-dev libboost-program-options-dev libboost-system-dev libboost-thread-dev libboost-wave-dev
    - gcc --version
    - cd src
    - qmake amarlon.pro
    - make
